### ISSUE TITLE
Small idea with return option

### ISSUE THREAD

**Issue by Allespro** [luxunator/menupy#2]
Hi, you have very cool project, but, can you please add return option
Example:

> import menupy
> 
> NewMenu = menupy.OptionMenu("Title", title_color="cyan")
> NewMenu.add_option("Option Selection #1")
> NewMenu.add_option("Option Selection #2", color="red")
> result = NewMenu.run()
> print(result)
result will be "Option Selection #1" or "Option Selection #2"

It would be convenient if:

> import menupy
> 
> NewMenu = menupy.OptionMenu("Title", title_color="cyan")
> NewMenu.add_option("Option Selection #1", return="choice1")
> NewMenu.add_option("Option Selection #2", color="red", return="select")
> result = NewMenu.run()
> print(result)
result will be "choice1" or "select"

Have a nice day)

**Comment by luxunator** [comment]
Hi thanks for giving this input. As a user of this module would you maybe give me an idea in where you would need to change the return other than the title? Just so then I know if this is something that needs to be done. Would not like to add options that just bloat the module :)

**Comment by Allespro** [comment]
@luxunator for example I create text game.
Player see console:

> Go to street

> Open the window

> Save game

That's uncomfortable, beacouse return will be 'Go to street' or 'Open the window', simple using return like 'gostreet', 'window', 'save'.

**Comment by luxunator** [comment]
Alright I will change the option menu and add a return for easier use.Should be fixed within the day. Thank you for your input it is valuable and hope that you enjoy the module and continue using it.

**Comment by luxunator** [comment]
Sorry for late update but option is added: luxunator/menupy@e6f59b2a5376b97bb9bf8a092174eff65a6bc245
